const cartItems = [
  {
    id: 1,
    name: 'Merry and Bright',
    maker: 'Nothing Bundt Cakes',
    price: 43,
    type: 'Cake',
    image: './img/Merry and Bright.png',
    amount: 1,
    rating: null,
  },
  {
    id: 2,
    name: 'Reindeer Dipped Strawberries',
    maker: "Shari's Berries",
    price: 50,
    type: 'Chocolate',
    image: './img/Reindeer Dipped Strawberries.png',
    amount: 1,
    rating: 4.8,
  },
  {
    id: 3,
    name: 'Christmas Cheer Petits Fours',
    maker: 'Swiss Colony',
    price: 28,
    type: 'Chocolate',
    image: './img/Christmas Cheer Petits Fours.png',
    amount: 1,
    rating: 4.7,
  },
  {
    id: 4,
    name: 'Red Velvet Christmas Trees and Hats',
    maker: 'Nothing Bundt Cakes',
    price: 42,
    type: 'Cake',
    image: './img/Red Velvet Christmas Trees and Hats.png',
    amount: 1,
    rating: null,
  },
  {
    id: 5,
    name: 'Holiday Tree Collection',
    maker: 'Neuhus',
    price: 67,
    type: 'Cookie',
    image: './img/Holiday Tree Collection.png',
    amount: 1,
    rating: null,
  },
  {
    id: 6,
    name: 'Snowman Gift Tower',
    maker: "Cheryl's Cookies",
    price: 45,
    type: 'Cookie',
    image: './img/Snowman Gift Tower.png',
    amount: 1,
    rating: null,
  },
];

export default cartItems;
